version: '3.8'

services:
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script

  script:
    image: php:7.4-fpm
    volumes:
      - ./app:/app
